name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - run: npm install
      - name: Instantiate github-keys.json
        run: 'echo "{ \"clientID\": \"clientID\", \"clientSecret\": \"clientSecret\", \"callbackURL\": \"http://localhost:3001/auth/github/callback\"}" > github-keys.json'
      - name: Instantiate blacklist
        run: echo {} > controller/atlasmakerServer/blacklist.json
      - name: Instantiate whitelist
        run: echo "{}" > controller/atlasmakerServer/whitelist.json
      - name: Instantiate websocket configuration file
        run: cp cfg.json.example cfg.json
      - run: npm run build
      - name: Run server
        run: timeout 3 npm start || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
      - name: Run mocha tests
        run: npm run mocha-test
      - name: Archive screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: test/screenshots/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
